[pytest]
log_cli = true
log_level = INFO
addopts = --alluredir=allure-results
markers =
    slow: marks tests as slow
    cart: Cart tests
    e2e: End to end tests
    navigation: Navigation tests
    cart: Cart tests
    login: Login tests
    ui: UI grid tests
    filtering: Filtering and sorting tests
    e2e: End to end flow tests
    database: Database validation tests
    math: Math validation tests
    select_options: Select options product tests
    home: Home page tests
    tea: Tea page tests
    teaware: Teaware page tests
testpaths =
    tests/test_navigation.py
    tests/test_home_page.py
    tests/test_tea_page.py
    tests/test_teawear.py
    tests/test_filtering_and_sorting.py
    tests/test_database_validation.py
    tests/test_ui_grids.py
    tests/test_login.py
    tests/test_cart.py
    tests/test_select_options_product.py
    tests/test_math_validations.py
    tests/test_e2e_flows.py

